ci: try reusable workflow
Signed-off-by: saan800 <sandragreenhalgh@gmail.com>

diff --git a/.github/workflows/_build_and_test.yml b/.github/workflows/_build_and_test.yml
--- a/.github/workflows/_build_and_test.yml
+++ b/.github/workflows/_build_and_test.yml
@@ -10,9 +10,6 @@ on:
         type: string
         default: "8.0"
 
-permissions:
-  checks: write
-
 jobs:
   build-and-test:
     name: build-and-test
@@ -36,14 +33,21 @@ jobs:
         run: dotnet build --no-restore --configuration Release
 
       - name: Run unit tests
-        run: dotnet test --no-restore --filter FullyQualifiedName~SaanSoft.Tests --logger "trx;LogFileName=unit-test-results.trx" --results-directory reports
+        run: dotnet test --no-restore --filter FullyQualifiedName~SaanSoft.Tests --logger "trx;LogFileName=unit-test-results-${{ inputs.runs-on }}-${{ inputs.dotnet-version }}.trx" --results-directory reports
 
-      - name: Upload test report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
+      - name: Upload dotnet test results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
         with:
-          # Name of the check run which will be created
-          name: Unit test results (${{ inputs.runs-on }} - ${{ inputs.dotnet-version }})
-          path: "reports/*.trx"
-          reporter: dotnet-trx
-          fail-on-error: true
+          name: unit-test-results-${{ inputs.runs-on }}-${{ inputs.dotnet-version }}
+          path: reports
+
+      # - name: Upload test report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     # Name of the check run which will be created
+      #     name: Unit test results (${{ inputs.runs-on }} - ${{ inputs.dotnet-version }})
+      #     path: "reports/*.trx"
+      #     reporter: dotnet-trx
+      #     fail-on-error: true
